name: Publish NPM Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'


jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mip-client-ts

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if ! npm publish --access public 2>&1 | grep -q "You cannot publish over the previously published version"; then
            exit 1
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            mip-client-ts/dist/*.js
            mip-client-ts/dist/*.d.ts
            mip-client-ts/LICENSE
            mip-client-ts/README.md
